[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/"
  to = "/docs/v2"
  status = 302
  force = true

[[redirects]]
  from = "/docs"
  to = "/docs/v2"
  status = 302
  force = true

[[redirects]]
  from = "/docs"
  to = "/docs/v3"
  status = 200

[[redirects]]
  from = "/docs/v3"
  to = "/v3/index.html"
  status = 200

[[redirects]]
  from = "/docs/v3/*"
  to = "/v3/:splat"
  status = 200

[[redirects]]
  from = "/docs/v2"
  to = "/v2/index.html"
  status = 200

[[redirects]]
  from = "/docs/v2/*"
  to = "/v2/:splat"
  status = 200

[[redirects]]
  from = "/changelog"
  to = "changelog.html"
  status = 200

[[redirects]]
  from = "https://tipser.dev"
  to = "https://developers.tipser.com"
  status = 302
  force = true

[[redirects]]
  from = "http://tipser.dev/*"
  to = "https://developers.tipser.com/:splat"
  status = 302

[[redirects]]
  from = "https://tipser.dev/*"
  to = "https://developers.tipser.com/:splat"
  status = 302

