[build]
  command = "middleman build --clean && npm run build-changelog"
  publish = "build"

[[redirects]]
 from = "/docs"
 to = "index.html"
 status = 200

 [[redirects]]
  from = "/changelog"
  to = "changelog.html"
  status = 200

[[redirects]]
  from = "http://tipser.dev"
  to = "https://developers.tipser.com"
  status = 302
  force = true

[[redirects]]
  from = "https://tipser.dev"
  to = "https://developers.tipser.com"
  status = 302
  force = true

[[redirects]]
  from = "http://tipser.dev/*"
  to = "https://developers.tipser.com/:splat"
  status = 302

[[redirects]]
  from = "https://tipser.dev/*"
  to = "https://developers.tipser.com/:splat"
  status = 302

