[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/"
  to = "/docs/v3/script"
  status = 302
  force = true

[[redirects]]
  from = "/docs"
  to = "/docs/v3/script"
  status = 302
  force = true

[[redirects]]
from = "/docs/v3"
to = "/docs/v3/script"
status = 302
force = true

[[redirects]]
  from = "/docs/v3/script"
  to = "/v3/script/index.html"
  status = 200

[[redirects]]
  from = "/docs/v3/elements"
  to = "/v3/elements/index.html"
  status = 200

[[redirects]]
  from = "/docs/v3/script/*"
  to = "/v3/script/:splat"
  status = 200

[[redirects]]
  from = "/docs/v3/elements/*"
  to = "/v3/elements/:splat"
  status = 200

[[redirects]]
  from = "/docs/v2"
  to = "/v2/index.html"
  status = 200

[[redirects]]
  from = "/docs/v2/*"
  to = "/v2/:splat"
  status = 200

[[redirects]]
  from = "/changelog"
  to = "changelog.html"
  status = 200

